//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfeEMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pfeEMPRESA()
        {
            this.pfeFACTURAS = new HashSet<pfeFACTURAS>();
            this.pfeFILIALES = new HashSet<pfeFILIALES>();
            this.pfeORDENCOMPRA = new HashSet<pfeORDENCOMPRA>();
            this.pfePROVEEDORES = new HashSet<pfePROVEEDORES>();
            this.pfeUSUARIOS = new HashSet<pfeUSUARIOS>();
        }
    
        public decimal IDEMPRESA { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string NOMCONTACTO { get; set; }
        public string EMAILCONTACTO { get; set; }
        public string TELEFONO { get; set; }
        public string ESTATUS { get; set; }
        public string RFC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFACTURAS> pfeFACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFILIALES> pfeFILIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeORDENCOMPRA> pfeORDENCOMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfePROVEEDORES> pfePROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeUSUARIOS> pfeUSUARIOS { get; set; }
    }
}
