//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfeFACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pfeFACTURAS()
        {
            this.pfeFACTURASDET = new HashSet<pfeFACTURASDET>();
        }
    
        public decimal IDFACTURA { get; set; }
        public decimal IDEMPRESA { get; set; }
        public decimal IDFILIAL { get; set; }
        public string IDPROVEEDOR { get; set; }
        public string IDFOLIOOC { get; set; }
        public string XMLTXT { get; set; }
        public string XMLOBJ { get; set; }
        public string XMLFILENAME { get; set; }
        public string PDFOBJ { get; set; }
        public string PDFFILENAME { get; set; }
        public string SERIE { get; set; }
        public string FOLIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal TOTAL { get; set; }
        public string MONEDA { get; set; }
        public string UUID { get; set; }
        public string ESTATUS { get; set; }
        public string COMENTARIO { get; set; }
        public string IMGOBJ { get; set; }
        public string IMGFILENAME { get; set; }
        public string TIPOCOMPROBANTE { get; set; }
        public Nullable<System.DateTime> FECHAINGRESOXML { get; set; }
        public Nullable<System.DateTime> FECHAINGRESOPDF { get; set; }
        public Nullable<System.DateTime> FECHAINGRESOIMG { get; set; }
        public Nullable<System.DateTime> FECHAESTATUS { get; set; }
    
        public virtual pfeEMPRESA pfeEMPRESA { get; set; }
        public virtual pfeFILIALES pfeFILIALES { get; set; }
        public virtual pfeORDENCOMPRA pfeORDENCOMPRA { get; set; }
        public virtual pfePROVEEDORES pfePROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFACTURASDET> pfeFACTURASDET { get; set; }
    }
}
