//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfeFACTURASDET
    {
        public decimal IDFACTURADET { get; set; }
        public decimal IDFACTURA { get; set; }
        public decimal IDEMPRESA { get; set; }
        public string CLAVEUNIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public string CANTIDAD { get; set; }
        public string VALORUNITARIO { get; set; }
        public string IMPORTE { get; set; }
    
        public virtual pfeFACTURAS pfeFACTURAS { get; set; }
    }
}
