//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfeORDENCOMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pfeORDENCOMPRA()
        {
            this.pfeFACTURAS = new HashSet<pfeFACTURAS>();
        }
    
        public decimal IDEMPRESA { get; set; }
        public decimal IDFILIAL { get; set; }
        public string IDPROVEEDOR { get; set; }
        public string IDFOLIOOC { get; set; }
        public System.DateTime FECHAOC { get; set; }
        public string OBRA { get; set; }
        public decimal COSTO { get; set; }
        public string MONEDA { get; set; }
        public string ESTATUS { get; set; }
        public string COMENTARIO { get; set; }
        public string IDUSUARIO { get; set; }
    
        public virtual pfeEMPRESA pfeEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFACTURAS> pfeFACTURAS { get; set; }
        public virtual pfeFILIALES pfeFILIALES { get; set; }
        public virtual pfePROVEEDORES pfePROVEEDORES { get; set; }
        public virtual pfeUSUARIOS pfeUSUARIOS { get; set; }
    }
}
