//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfePROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pfePROVEEDORES()
        {
            this.pfeFACTURAS = new HashSet<pfeFACTURAS>();
            this.pfeORDENCOMPRA = new HashSet<pfeORDENCOMPRA>();
        }
    
        public decimal IDEMPRESA { get; set; }
        public string IDPROVEEDOR { get; set; }
        public string RAZONSOCIAL { get; set; }
        public string TIPOPROV { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string TIPOPAGO { get; set; }
        public decimal DIASCREDITO { get; set; }
        public string TIPOFACTURA { get; set; }
        public string TIPOVENCE { get; set; }
        public string CLAVEPROV { get; set; }
        public string CLAVEPROD { get; set; }
        public string NOMCONTACTO { get; set; }
        public string APPCONTACTO { get; set; }
        public string APMCONTACTO { get; set; }
        public string EMAILPROV { get; set; }
        public string TELEFONO { get; set; }
        public string IDUSUARIO { get; set; }
        public string IDMODIFICA { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual pfeEMPRESA pfeEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFACTURAS> pfeFACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeORDENCOMPRA> pfeORDENCOMPRA { get; set; }
        public virtual pfeUSUARIOS pfeUSUARIOS { get; set; }
    }
}
