//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pfeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pfeUSUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pfeUSUARIOS()
        {
            this.pfeFILIALES = new HashSet<pfeFILIALES>();
            this.pfeORDENCOMPRA = new HashSet<pfeORDENCOMPRA>();
            this.pfePROVEEDORES = new HashSet<pfePROVEEDORES>();
        }
    
        public decimal IDEMPRESA { get; set; }
        public string IDUSUARIO { get; set; }
        public string PASSW { get; set; }
        public string NOMUSUARIO { get; set; }
        public string ROL { get; set; }
        public string ESTATUS { get; set; }
    
        public virtual pfeEMPRESA pfeEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeFILIALES> pfeFILIALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfeORDENCOMPRA> pfeORDENCOMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pfePROVEEDORES> pfePROVEEDORES { get; set; }
    }
}
